import { useEffect, useState } from "react";
import { Plus, Search } from "lucide-react";
import { toast } from "sonner";
import { problemaTipicoService } from "../services/problemaTipicoService";
import type { ProblemaTipico } from "../types/problemaTipico";

export default function ProblemasTipicosPage(){
 const [items,setItems]=useState<ProblemaTipico[]>([]),[busca,setBusca]=useState(""),[ativo,setAtivo]=useState<string>("");
 const carregar=()=>problemaTipicoService.listar({busca:busca||undefined,ativo:ativo===""?undefined:ativo==="true"}).then(r=>setItems(r.data)).catch(()=>toast.error("Erro ao carregar a base."));
 useEffect(()=>{carregar()},[ativo]);
 const alternar=async(p:ProblemaTipico)=>{await problemaTipicoService.status(p.id_problema,!p.ativo);carregar()};
 return <div className="mx-auto max-w-7xl space-y-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-bold text-slate-900">Problemas Típicos</h1><p className="text-slate-500">Base de conhecimento de manutenção</p></div><a href="/ss/nova" className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2 text-white"><Plus size={17}/>Cadastrar pela SS</a></div><div className="flex flex-wrap gap-2 rounded-xl border bg-white p-4"><label className="flex min-w-72 flex-1 items-center gap-2 rounded-lg border px-3"><Search size={17}/><input className="w-full py-2 outline-none" value={busca} onChange={e=>setBusca(e.target.value)} onKeyDown={e=>e.key==='Enter'&&carregar()} placeholder="Título, descrição, modo de falha, sintoma ou causa"/></label><select className="rounded-lg border px-3" value={ativo} onChange={e=>setAtivo(e.target.value)}><option value="">Todos</option><option value="true">Ativos</option><option value="false">Inativos</option></select><button className="rounded-lg bg-slate-900 px-4 text-white" onClick={carregar}>Pesquisar</button></div><div className="overflow-hidden rounded-xl border bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-slate-600"><tr><th className="p-3">Problema</th><th className="p-3">Sistema/Categoria</th><th className="p-3">Criticidade</th><th className="p-3">Especialidade</th><th className="p-3">Status</th><th className="p-3">Ações</th></tr></thead><tbody>{items.map(p=><tr key={p.id_problema} className="border-t align-top"><td className="p-3"><details><summary className="cursor-pointer font-semibold">{p.titulo}</summary><div className="mt-2 max-w-xl space-y-1 text-slate-600"><p>{p.descricao}</p><p><b>Sintomas:</b> {p.sintomas.map(x=>x.sintoma).join('; ')}</p><p><b>Causas:</b> {p.causas.map(x=>x.causa).join('; ')}</p></div></details></td><td className="p-3">{p.sistema}<br/><span className="text-slate-500">{p.categoria}</span></td><td className="p-3">{p.criticidade_padrao}</td><td className="p-3">{p.especialidade||'—'}</td><td className="p-3">{p.ativo?'Ativo':'Inativo'}</td><td className="p-3"><button className="rounded border px-2 py-1" onClick={()=>alternar(p)}>{p.ativo?'Desativar':'Ativar'}</button></td></tr>)}</tbody></table>{!items.length&&<p className="p-8 text-center text-slate-500">Nenhum problema encontrado.</p>}</div></div>
}
