import { useEffect, useMemo, useState } from "react";
import { Plus, Search, X } from "lucide-react";
import { toast } from "sonner";
import { problemaTipicoService } from "../services/problemaTipicoService";
import type { ProblemaPayload, ProblemaTipico, SSProblema } from "../types/problemaTipico";

const vazio=(id:number):ProblemaPayload=>({id_tipo_ativo:id,sistema:"Subestação",categoria:"Elétrica",titulo:"",descricao:"",criticidade_padrao:"MEDIA",modo_falha:"",efeito_falha:"",detectabilidade:"MEDIA",especialidade:"Manutenção elétrica",requer_desligamento:false,ativo:true,sintomas:[],causas:[],acoes_recomendadas:[],metodos_deteccao:[]});
export default function ProblemasSS({idTipoAtivo,value,onChange}:{idTipoAtivo?:number|null;value:SSProblema[];onChange:(v:SSProblema[])=>void}){
 const [lista,setLista]=useState<ProblemaTipico[]>([]),[busca,setBusca]=useState(""),[modal,setModal]=useState(false),[novo,setNovo]=useState<ProblemaPayload|null>(null);
 const carregar=()=>idTipoAtivo?problemaTipicoService.porTipo(idTipoAtivo).then(r=>setLista(r.data)).catch(()=>toast.error("Não foi possível carregar os problemas típicos.")):setLista([]);
 useEffect(()=>{carregar()},[idTipoAtivo]);
 const filtrada=useMemo(()=>lista.filter(p=>(p.titulo+" "+(p.descricao||"")).toLowerCase().includes(busca.toLowerCase())),[lista,busca]);
 const toggle=(p:ProblemaTipico)=>onChange(value.some(x=>x.id_problema===p.id_problema)?value.filter(x=>x.id_problema!==p.id_problema):[...value,{id_problema:p.id_problema,criticidade_identificada:p.criticidade_padrao,confirmado:false,problema:p}]);
 const addTexto=(campo:"sintomas"|"causas"|"metodos_deteccao")=>{const texto=prompt(`Informe ${campo.replace("_"," ")}:`)?.trim();if(!texto||!novo)return;setNovo({...novo,[campo]:[...novo[campo],campo==="sintomas"?{sintoma:texto}:campo==="causas"?{causa:texto}:{metodo:texto}]})};
 const salvar=async()=>{if(!novo?.titulo.trim())return toast.error("Informe o título.");try{const p=(await problemaTipicoService.criar(novo)).data;setLista(x=>[...x,p]);onChange([...value,{id_problema:p.id_problema,criticidade_identificada:p.criticidade_padrao,confirmado:false,problema:p}]);setModal(false);toast.success("Problema cadastrado e selecionado.")}catch{toast.error("Erro ao cadastrar problema.")}};
 return <section className="rounded-xl border border-slate-200 bg-slate-50 p-4 md:p-5">
  <div className="mb-3 flex flex-wrap items-center justify-between gap-2"><div><h3 className="font-semibold text-slate-900">Problemas identificados</h3><p className="text-sm text-slate-500">Base filtrada automaticamente pelo tipo do ativo.</p></div><button type="button" disabled={!idTipoAtivo} onClick={()=>{setNovo(vazio(idTipoAtivo!));setModal(true)}} className="inline-flex items-center gap-1 rounded-lg border bg-white px-3 py-2 text-sm disabled:opacity-50"><Plus size={16}/> Cadastrar novo problema</button></div>
  {!idTipoAtivo?<p className="text-sm text-slate-500">Selecione um ativo para consultar a base.</p>:<><label className="mb-3 flex items-center gap-2 rounded-lg border bg-white px-3"><Search size={16}/><input className="w-full border-0 bg-transparent py-2 outline-none" value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Pesquisar problema..."/></label><div className="grid max-h-[360px] gap-2 overflow-y-auto overscroll-contain pr-1 [scrollbar-gutter:stable]">{filtrada.map(p=><details key={p.id_problema} className="rounded-lg border bg-white p-3"><summary className="cursor-pointer list-none"><label className="flex cursor-pointer items-center gap-2"><input type="checkbox" checked={value.some(x=>x.id_problema===p.id_problema)} onChange={()=>toggle(p)}/><strong className="flex-1">{p.titulo}</strong><span className="rounded-full bg-slate-100 px-2 py-1 text-xs">{p.criticidade_padrao}</span></label></summary><div className="mt-3 grid gap-2 border-t pt-3 text-sm text-slate-600"><p>{p.descricao}</p><p><b>Sintomas:</b> {p.sintomas.map(x=>x.sintoma).join("; ")||"Não informados"}</p><p><b>Causas:</b> {p.causas.map(x=>x.causa).join("; ")||"Não informadas"}</p><p><b>Ações:</b> {p.acoes_recomendadas.map(x=>x.descricao).join("; ")||"Não informadas"}</p></div></details>)}</div></>}
  {value.map((x,i)=><div key={x.id_problema} className="mt-3 rounded-lg border border-blue-200 bg-blue-50 p-3"><div className="mb-2 flex justify-between"><strong>{x.problema?.titulo||lista.find(p=>p.id_problema===x.id_problema)?.titulo}</strong><button type="button" onClick={()=>onChange(value.filter((_,j)=>j!==i))}><X size={16}/></button></div><textarea className="w-full rounded border p-2 text-sm" placeholder="Observação específica desta SS" value={x.observacao||""} onChange={e=>onChange(value.map((v,j)=>j===i?{...v,observacao:e.target.value}:v))}/></div>)}
  {modal&&novo&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/50 p-4"><div className="max-h-[90vh] w-full max-w-3xl overflow-auto rounded-xl bg-white p-5 shadow-xl"><div className="mb-4 flex justify-between"><h3 className="text-lg font-semibold">Novo problema típico</h3><button onClick={()=>setModal(false)}><X/></button></div><div className="grid gap-3 md:grid-cols-2">{([['titulo','Título'],['sistema','Sistema'],['categoria','Categoria'],['especialidade','Especialidade'],['modo_falha','Modo de falha'],['efeito_falha','Efeito da falha']] as const).map(([k,l])=><label className="grid gap-1 text-sm" key={k}>{l}<input className="rounded border p-2" value={String(novo[k]||"")} onChange={e=>setNovo({...novo,[k]:e.target.value})}/></label>)}<label className="grid gap-1 text-sm">Criticidade<select className="rounded border p-2" value={novo.criticidade_padrao} onChange={e=>setNovo({...novo,criticidade_padrao:e.target.value as any})}>{['BAIXA','MEDIA','ALTA','CRITICA'].map(x=><option key={x}>{x}</option>)}</select></label><label className="flex items-center gap-2"><input type="checkbox" checked={novo.requer_desligamento} onChange={e=>setNovo({...novo,requer_desligamento:e.target.checked})}/> Requer desligamento</label></div><label className="mt-3 grid gap-1 text-sm">Descrição<textarea className="rounded border p-2" value={novo.descricao||""} onChange={e=>setNovo({...novo,descricao:e.target.value})}/></label><div className="mt-3 flex flex-wrap gap-2"><button className="rounded border px-3 py-2" onClick={()=>addTexto('sintomas')}>+ Sintoma ({novo.sintomas.length})</button><button className="rounded border px-3 py-2" onClick={()=>addTexto('causas')}>+ Causa ({novo.causas.length})</button><button className="rounded border px-3 py-2" onClick={()=>addTexto('metodos_deteccao')}>+ Método ({novo.metodos_deteccao.length})</button><button className="rounded border px-3 py-2" onClick={()=>{const descricao=prompt('Informe a ação recomendada:')?.trim();if(descricao)setNovo({...novo,acoes_recomendadas:[...novo.acoes_recomendadas,{tipo_acao:'INVESTIGACAO',descricao}]})}}>+ Ação ({novo.acoes_recomendadas.length})</button></div><div className="mt-5 flex justify-end gap-2"><button className="rounded border px-4 py-2" onClick={()=>setModal(false)}>Cancelar</button><button className="rounded bg-blue-600 px-4 py-2 text-white" onClick={salvar}>Salvar e selecionar</button></div></div></div>}
 </section>
}
